### PR TITLE
Python 3.8 support

### PR DESCRIPTION
**Pull request by richardARPANET**
```
  /home/work/.pyenv/versions/3.7.4/envs/wwwww/lib/python3.7/site-packages/orderedset/__init__.py:5: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from ._orderedset import OrderedSet
```

Fixes the above warning.

### CODE REVIEW

**Comment by richardARPANET** [comment]
@simonpercivall Could you review this please?

**Comment by leonardt** [comment]
Bump! Let's get this warning fixed (this should be a <1 min review)

**Comment by azmeuk** [comment]
@simonpercivall Could you please take some time to merge this?
If you do not want to maintain this project anymore, would you consider letting some other people to help you?

**Comment by simonpercivall** [comment]
Thanks for the patch, and for the bumps. New version out.

**Comment by azmeuk** [comment]
Great news. Thank you!

**Pull request merged**
